# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://cdn.cocoapods.org/'
target 'LYYFixCodeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LYYFixCodeDemo
  pod 'Aspects'
  target 'LYYFixCodeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYYFixCodeDemoUITests' do
    # Pods for testing
  end

end
